---
- name: Apache server installed
  hosts: web
  become: yes
  
  vars:
    file_path: /var/www/html/index.html
  
  tasks:
  - name: latest Apache version installed
    yum:
      name: httpd
      state: latest
  - name: Apache enabled and running
    service:
      name: httpd
      enabled: true
      state: started
  - name: copy index.html
    template:
      src: index.j2
      dest: "{{ file_path }}"
