---
- name: change request verification
  hosts: web
  gather_facts: true
  
  vars:
    table: incident
    state: present
  
  
  tasks:

  - name: verify change request "{{ change_request_number }}"
    snow_record:
      state: "{{ state }}" 
      table: "{{ table }}"
      username: "{{ SN_USERNAME }}"
      password: "{{ SN_PASSWORD }}"
      instance: "{{ SN_INSTANCE }}"
     # number: "{{ change_request_number }}"
      data:
      #  priority: "{{ priority }}"
     #   u_device_up_time: "{{ system_facts.uptime }}"
     #   u_ios_version: "{{ system_facts.version }}"
     #   u_hostname: "{{ inventory_hostname }}"
        short_description: "This ticket was created by Ansible"
    register: change_request
    delegate_to: localhost
    
  - debug: var=change_request.record
  
  - debug: var=ansible_facts.architecture
  - debug: var=ansible_facts.bios_version
  - debug: var=ansible_facts.distribution
