---
- name: "{{ pack }}" yum install
  hosts: web
  become: yes
  
  
  tasks:
  - name: latest "{{ pack }}" version installed
    yum:
      name: "{{ pack }}"
      state: latest
      
      
      
  - name: "{{ pack }}" enabled and running
    service:
      name: "{{ pack }}"
      enabled: true
      state: started
